### ISSUE TITLE
Pull request?

### ISSUE THREAD

**Issue by dtow55** [learn-co-curriculum/react-components#4]
This lab requires a fork and pull request, but in the Readme, it does not tell us to write any code, and in the file on github, there is no file in which to write the code. Was this lesson mistakenly created as a lab?

**Comment by hansenjl** [comment]
A few students have asked how to complete this code along because the github repo doesn't have a set up that students can easily add code to. I think this lesson should either be one that is marked as complete or revised to include code for students to add to. 

@Alicekb

**Comment by DanielSeehausen** [comment]
thank you @dtow55 and @hansenjl 
should be fixed now! let me know if you have any problems
